src/chatter/chat/urls.py
from django.conf.urls import url

from . import views

app_name = "chat"

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^create_chatroom/$', views.create_chatroom, name="create_chatroom"),
    url(r'^(?P<chatroom_id>[0-9]+)/$', views.chatroom, name="chatroom"),
    url(r'^(?P<chatroom_id>[0-9]+)/post$', views.chatroom_post, name="chatroom_post"),
    url(r'^(?P<chatroom_id>[0-9]+)/challenge/$',
        views.chatroom_password_challenge, name="chatroom_password_challenge"),
    url(r'^register_user/$', views.register_user, name="register_user"),
]

src/chatter/chatter/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    #url(r'^login/$', auth_views.login, name="login"),
    #url(r'^logout/$', auth_views.logout, name="logout"),
    url(r'^', include("django.contrib.auth.urls")),
    url(r'^', include('chat.urls')),
    url(r'^admin/', admin.site.urls),
]

src/chatter/chat/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

CHARFIELD_MAX = 4000

class Profile(models.Model):
    """ Author. """
    user = models.OneToOneField(User)
    nick = models.CharField(max_length=80)

    def __str__(self):
        return self.nick

class Chatroom(models.Model):
    """ Chatroom. """
    title = models.CharField(max_length=80)
    description = models.CharField(max_length=300)
    # Password is optional. Blank means no password.
    password = models.CharField(max_length=CHARFIELD_MAX, blank=True)
    creator = models.ForeignKey(Profile)

    def __str__(self):
        return self.title

class Post(models.Model):
    """ Message. """
    content = models.CharField(max_length=CHARFIELD_MAX)
    publish_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(Profile)
    chatroom = models.ForeignKey(Chatroom)

    def __str__(self):
        return self.content

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    """ Create Profile model when user is created. """
    if created:
        Profile.objects.create(user=instance, nick=instance.username)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    """ Save Profile model when user is saved. """
    instance.profile.save()

src/chatter/chat/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404, redirect
from django.urls import reverse
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import check_password, make_password
from .models import Chatroom, Profile, Post

SESSION_ROOM_KEY_PREFIX = "chatroom"

def index(request):
    rooms = Chatroom.objects.all()
    return render(request, "chat/index.html", {"chatrooms": rooms})
"""
def profile(request, profile_id):
    profile = get_object_or_404()
"""
@login_required
def create_chatroom(request):
    render_template_name = "chat/create_chatroom.html"
    if request.method == "GET":
        return render(request, render_template_name)

    title = request.POST.get("title", None)
    description = request.POST.get("description", None)
    password = request.POST.get("password", None)
    password_retry = request.POST.get("password_retry", None)
    errors = []
    # Validation...
    if password != password_retry:
        errors.append("Passwords did not match.")
    if not password or password.isspace():
        password = ""
    if not title:
        errors.append("No title.")

    try:
        creator = Profile.objects.get(user=request.user)
    except Profile.DoesNotExist:
        errors.append(
            "Could not retrive your profile information. Try logging out then logging back in.")
    except Profile.MultipleObjectsReturned:
        errors.append(
            "You appear to have multiple profiles, this should not be possible. This needs to be fixed before a chatroom can be made.")

    if errors:
        return render(request, render_template_name, {"errors": errors})

    # By this point, we should be all good to make a chatroom...
    if password: # We store password as hash. Chatrooms be so secure.
        password = make_password(password)

    room = Chatroom.objects.create(
        title=title,
        description=description,
        password=password,
        creator=creator)

    if room:
        return redirect("chat:chatroom", int(room.id))
    else:
        errors.append("Failed to create room, sorry. Try again.")
        return render(request, render_template_name, {"errors":errors})

def chatroom(request, chatroom_id):
    render_template_name = "chat/chatroom.html"
    room = get_object_or_404(Chatroom, pk=chatroom_id)
    # The key used when storing room's login status in the session.
    # Must match what is set by the challenge.
    session_room_key = SESSION_ROOM_KEY_PREFIX + str(chatroom_id)
    if room.password and not room.password.isspace():
        if not request.session.get(session_room_key, None) == str(True):
            return redirect("chat:chatroom_password_challenge", int(chatroom_id))
    # By this point, the we should be safe to show the chat.
    messages = Post.objects.filter(chatroom=room.id)
    context = {"chatroom": room, "messages": messages}
    return render(request, render_template_name, context)

def chatroom_post(request, chatroom_id):
    room = get_object_or_404(Chatroom, pk=chatroom_id)
    # The key used when storing room's login status in the session.
    # Must match what is set by the challenge.
    session_room_key = SESSION_ROOM_KEY_PREFIX + str(chatroom_id)
    if room.password and not room.password.isspace():
        if not request.session.get(session_room_key, None) == str(True):
            return redirect("chat:chatroom_password_challenge", int(chatroom_id))
    if not request.user.is_authenticated:
        return redirect("chat:chatroom", int(chatroom_id))
    # By this point, we should be safe to create a message...
    message_content = request.POST.get("message", None)
    if not message_content:
        return redirect("chat:chatroom", int(chatroom_id))
    message_author = Profile.objects.get(user=request.user)
    Post.objects.create(
        content=message_content,
        author=message_author,
        chatroom=room)
    return redirect("chat:chatroom", int(chatroom_id))

def chatroom_password_challenge(request, chatroom_id):
    """ On success, sets the session object to have a chatroom-unique key, with value of "True".
        Otherwise does not set anything.
        Key is computed like this:
            SESSION_ROOM_KEY_PREFIX + str(room.id)"""
    render_template_name = "chat/chatroom_password_challenge.html"
    room = get_object_or_404(Chatroom, pk=chatroom_id)
    # The key used when storing room's login status in the session.
    session_room_key = SESSION_ROOM_KEY_PREFIX + str(room.id)

    if request.method == "GET":
        # May have already logged in to the room, recently.
        if request.session.get(session_room_key, None) == str(True):
            return redirect("chat:chatroom", int(room.id))
        else:
            return render(request, render_template_name, {"chatroom": room})

    password_attempt = request.POST.get("password", None)
    if check_password(password_attempt, room.password):
        request.session[SESSION_ROOM_KEY_PREFIX+str(room.id)] = str(True)
        return redirect("chat:chatroom", int(room.id))
    else:
        return render(request, render_template_name, {"chatroom": room})

def register_user(request):
    render_template_name = "chat/register.html"
    if request.method == "GET":
        return render(request, render_template_name)

    username = request.POST.get("username", None)
    email = request.POST.get("email", None)
    password = request.POST.get("password", None)
    password_retry = request.POST.get("password_retry", None)
    errors = []
    # Validation...
    if not username:
        errors.append("Username is required.")
    if not email:
        errors.append("Email is required.")
    if not password or not password_retry:
        errors.append("Password fields are required.")
    if password != password_retry:
        errors.append("Passwords did not match.")
    if errors:
        return render(request, render_template_name, {"errors": errors})
    # By this point, we should be all good to create user.
    user, created = User.objects.get_or_create(username=username, email=email)

    if created:
        user.set_password(password)
        user.save()
        return redirect(reverse("login"))
    else:
        errors.append("You seem to be already registered.")
        return render(request, render_template_name, {
            "errors": errors})

src/chatter/chat/templates/chat/chatroom.html
{% extends "base.html" %}

{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static "chat/chat_ui.css" %}" >
{% endblock head %}

{% block title %}Chatroom - {{ chatroom.title }}{% endblock %}

{% block content %}
<div class="row">
    <div class="col-xs-12"><h1>{{ chatroom.title }}</h1></div>
</div>

<div class="row">
    <div class="col-xs-12">
        <h2>Description</h2>
        <p>{{ chatroom.description }}</p>
    </div>
</div>

<div class="row">
    <div class="col-xs-12">
        <div class="form-group">
            <textarea id="chat_messages"
            class="form-control chat-messages"
            wrap="soft"
            rows="{{messages|length}}"
            readonly>{% for message in messages %}
({{ message.author.nick }}) [{{ message.publish_date }}]: {{ message.content }}{% endfor %}</textarea>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-xs-12">
        <form class="form-horizontal" method="POST" action="{% url "chat:chatroom_post" chatroom.id %}">
            {% csrf_token %}
            <div class="form-group">
                <label class="col-xs-2" for="form-chatroom-new-message">Message</label>
                <div class="col-xs-8">
{% if user.is_authenticated %}
                    <input class="form-control" id="form-chatroom-new-message" type="text" name="message" autofocus>
{% else %}
                    <input disabled class="form-control" id="form-chatroom-new-message" type="text" name="message" placeholder="You must be logged in to send messages.">
{% endif %}
                </div>
                <div class="col-xs-2">
{% if user.is_authenticated %}
                    <button class="btn btn-primary" type="submit">Submit</button>
{% else %}
                    <button disabled class="btn btn-primary" type="submit">Submit</button>
{% endif %}
                </div>
            </div>
        </form>
    </div>
</div>

{% endblock content %}

{% block javascript %}
<script src="{% static "chat/chat_ui.js" %}"></script>
{% endblock javascript %}

src/chatter/chat/templates/chat/chatroom_password_challenge.html
{% extends "base.html" %}

{% block title %}Chatroom Login{% endblock %}

{% block content %}
<div class="row">
    <div class="col-xs-12"><h1>Chatroom Login</h1></div>
</div>

{% if errors %}
    <div class="row">
        <div class="col-xs-12">
            <ul class="list-unstyled">
                {% for error in errors %}
                <li>
                    <div class="alert alert-danger">
                        {{ error }}
                    </div>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endif %}

<div class="row">
    <div class="col-xs-12">
        <div class="alert alert-warning">
            <p>This chatroom is locked with a password, please enter it to access.</p>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-xs-12">
        <form method="POST" action="{% url "chat:chatroom_password_challenge" chatroom.id %}">
            {% csrf_token %}
            <div class="form-group">
                <label for="form-chatroom-password">Password</label>
                <input class="form-control" id="form-chatroom-password" type="password" name="password">
            </div>
            <button class="btn btn-primary" type="submit">Submit</button>
        </form>
    </div>
</div>

{% endblock content %}

src/chatter/chat/templates/chat/create_chatroom.html
{% extends "base.html" %}

{% block title %}Create Chatroom{% endblock %}

{% block content %}
<div class="row">
    <div class="col-xs-12"><h1>Create Chatroom</h1></div>
</div>

{% if user.is_authenticated %}
    {% if errors %}
        <div class="row">
            <div class="col-xs-12">
                <ul class="list-unstyled">
                {% for error in errors %}
                    <li>
                        <div class="alert alert-danger">
                            {{ error }}
                        </div>
                    </li>
                {% endfor %}
                </ul>
            </div>
        </div>
    {% endif %}

    <div class="row">
        <div class="col-xs-12">
            <form method="POST" action="{% url "chat:create_chatroom" %}">
                {% csrf_token %}
                <div class="form-group">
                    <label for="form-chatroom-title">Title</label>
                    <input class="form-control" id="form-chatroom-title" type="text" name="title" placeholder="Some Title">
                </div>
                <div class="form-group">
                    <label for="form-chatroom-description">Description</label>
                    <input class="form-control" id="form-chatroom-description" type="text" name="description" placeholder="This room is about...">
                </div>
                <div class="form-group">
                    <label for="form-chatroom-password">Password</label>
                    <input class="form-control" id="form-chatroom-password" type="password" name="password" aria-describedby="form-chatroom-password-description">
                    <span id="form-chatroom-password-description" class="help-block">If left empty, anyone will be able to join.</span>
                    <label for="form-chatroom-password-retry">Password (again)</label>
                    <input class="form-control" id="form-chatroom-password-retry" type="password" name="password_retry" aria-describedby="form-chatroom-password-description">
                </div>
                <button class="btn btn-primary" type="submit">Create</button>
            </form>
        </div>
    </div>

{% else %}
    <div class="row">
        <div class="col-xs-12">
            <div class="alert alert-danger">
                <p>You need to be logged in to create chatrooms.</p>
            </div>
        </div>
    </div>
{% endif %}

{% endblock content %}

src/chatter/chat/templates/chat/index.html
{% extends "base.html" %}

{% block title %}Chatroom - {{ chatroom.title }}{% endblock %}

{% block content %}
<div class="row">
    <div class="col-xs-12"><h1>{{ chatroom.title }}</h1></div>
</div>

{% if chatrooms %}
    <table class="table table-condensed table-striped">
        <thead>
            <tr>
                <th>Name</th>
                <th>Password</th>
            </tr>
        </thead>
        <tbody>
            {% for room in chatrooms %}
                <tr>
                    <td><a href="{% url 'chat:chatroom' room.id %}">{{ room.title }}</a></td>
                    {% if room.password and not room.password.isspace %}
                        <td><span class="glyphicon glyphicon-lock"></span><span class="sr-only">Has password.</span></td>
                    {% else %}
                        <td><span class="sr-only">Does not have password.</span></td>
                    {% endif %}
                </tr>
            {% endfor %}
        <tbody>
    </table>
{% else %}
    <div class="alert alert-warning">
        <p>No rooms found!</p>
    </div>
{% endif %}
{% endblock content %}

src/chatter/chat/templates/chat/register.html
{% extends "base.html" %}

{% block title %}Register{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-xs-12"><h1>Register</h1></div>
    </div>

    {% if errors %}
        <div class="row">
            <div class="col-xs-12">
                <ul class="list-unstyled">
                {% for error in errors %}
                    <li>
                        <div class="alert alert-danger">
                            {{ error }}
                        </div>
                    </li>
                {% endfor %}
                </ul>
            </div>
        </div>
    {% endif %}
    
    {% if user.is_authenticated %}

    <div class="row">
        <div class="col-xs-12">
            <div class="alert alert-info">
                <p>You are already logged in.</p>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12">
            <div class="alert alert-info">
                <a href="{% url "chat:index" %}">Home</a>
            </div>
        </div>
    </div>
        
    {% else %}

    <div class="row">
        <div class="col-xs-12">
            <form method="POST" action="{% url "chat:register_user" %}">
                {% csrf_token %}
                <div class="form-group">
                    <label for="form-register-username">Username</label>
                    <input class="form-control" id="form-register-username" type="text" name="username" placeholder="Username">
                </div>
                <div class="form-group">
                    <label for="form-register-email">Email</label>
                    <input class="form-control" id="form-register-email" type="email" name="email" placeholder="you@somewhere.something">
                </div>
                <div class="form-group">
                    <label for="form-register-password">Password</label>
                    <input class="form-control" id="form-register-password" type="password" name="password">
                    <label for="form-register-password-retry">Password (again)</label>
                    <input class="form-control" id="form-register-password-retry" type="password" name="password_retry">
                </div>
                <button class="btn btn-primary" type="submit">Register</button>
            </form>
        </div>
    </div>

    {% endif %}
    

{% endblock content %}

src/chatter/templates/_nav.html
<nav class="navbar navbar-fixed-top navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-menu" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'chat:index' %}">Chatter</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="navbar-menu">
        <a class="btn btn-default navbar-btn" href="{% url 'chat:create_chatroom' %}">New Room</a>
      <ul class="nav navbar-nav navbar-right">
          {% if user.is_authenticated %}
            <li><a href="{% url 'password_change' %}">{{ user.Profile.nick }}</a></li>
            <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li><a href="{% url 'login' %}">Login</a></li>
            <li><a href="{% url 'chat:register_user' %}">Register</a></li>
          {% endif %}
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

src/chatter/templates/base.html
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <!-- theme -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
        <title>{% block title %}Chatter{% endblock %}</title>
        {% block head %}
        {% endblock %}
    </head>
    <body style="padding-top:70px">
        {% include "_nav.html" %}
        <section class="container">
            {% block content %}
            {% endblock %}
        </section>

        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <!-- Latest compiled and minified JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

        {% block javascript %}
        {% endblock %}
    </body>
</html>